### ISSUE TITLE
Open textbook?

### ISSUE THREAD

**Issue by Alex-Linhares** [msbrogli/sdm-framework#6]
Here's an idea for the future:  what if we created [the beggining of] an open textbook for SDM?  Something that could teach novices both about the framework and about the theory, and had multiple graphs that Kanerva generated, now done through code.  

*Since all papers published on Open Access Journals **already are Creative-Commons**, it would be a matter of copying and pasting (and citing/accrediting) those papers that already are open*.  That could speed things up and bring quality to a higher-level, if the papers and results turn out to be interesting.  

At any rate, as I look for cool things to do it the future, this is definitely one that I'll consider.

**Comment by msbrogli** [comment]
We could use the documentation of this project to do this. It will be available in http://sdm-framework.readthedocs.io/.
